name: 2-Jobs-diffrent-OS
on: 
  workflow_dispatch:

jobs:
  windows-job:
    runs-on: windows-latest
    steps:
      - name: checkout-repo
        uses: action/checkout@v2
      
      - name: check files
        run: |
         pwd
         ls
      
            
    
      
  
